### ISSUE TITLE
doesn't compile on macOS

### ISSUE THREAD

**Issue by SwiftAppx** [fg123/wendy#47]
hi,
doesn't compile on macOS
the problem is the in file ast.c
line 687 enum opcode code; 
error variable 'code' is used uninitialized whenever switch default is taken
what is default value ?

**Comment by fg123** [comment]
Yeah, so the default case is there so the compiler doesn't complain about the cases not handled, but we already filter out the other cases through the higher level switch statement. I've added a default initialized value that should fix your compiler error.

**Comment by SwiftAppx** [comment]
thanks,
