### ISSUE TITLE
Array initialization using * operator fails memory allocation on negative numbers

### ISSUE THREAD

**Issue by wchlhyun** [fg123/wendy#54]
`[0] * -1;`

results in

`Could not allocate memory! Out of memory?Program Stopped.`

https://wendy.felixguo.me/code/?code=WzBdICogLTE7

need to check for negative values at https://github.com/fg123/wendy/blob/master/src/vm.c#L1279

**Comment by fg123** [comment]
Fixed in https://github.com/fg123/wendy/commit/1ad3a1803d951b50b3551922ebe428ed8eea2777
